apiVersion: apps/v1
kind: Deployment
metadata: 
  name: svc1-deployment
spec:
  replicas: {{ default 1 .Values.replicaCount | int }}
  selector:
    matchLabels:
      app: hometrialsvc1
  template:
    metadata:
      labels:
        app: hometrialsvc1
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image }}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: acr-auth  
---
apiVersion: v1
kind: Service
metadata:
  name: svc1-svc
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    protocol: TCP
    name: {{ .Values.service.name }}
  selector:
    app: hometrialsvc1
    