apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: homesvc1-default
  namespace: default
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:1.0.*
spec:
  chart:
    git: git@github.com:SachinKut/homefluxstuff.git
    path: charts/homecharts
  releaseName: homesvc1-default
  values:
    image: sachakstestreg.azurecr.io/hometrialsvc1:1.0.0